# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(400, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 240))
        MainWindow.setMaximumSize(QtCore.QSize(400, 240))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/main_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(MainWindow)
        self.buttonBox.setGeometry(QtCore.QRect(0, 200, 391, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(MainWindow)
        self.frame.setGeometry(QtCore.QRect(0, -10, 401, 199))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_icon = QtWidgets.QLabel(self.frame)
        self.lbl_icon.setGeometry(QtCore.QRect(30, 60, 81, 81))
        self.lbl_icon.setText("")
        self.lbl_icon.setPixmap(QtGui.QPixmap(":/icon/main_icon"))
        self.lbl_icon.setScaledContents(True)
        self.lbl_icon.setObjectName("lbl_icon")
        self.lbl_title = QtWidgets.QLabel(self.frame)
        self.lbl_title.setGeometry(QtCore.QRect(140, 40, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_version = QtWidgets.QLabel(self.frame)
        self.lbl_version.setGeometry(QtCore.QRect(140, 75, 221, 16))
        self.lbl_version.setObjectName("lbl_version")
        self.lbl_notice = QtWidgets.QLabel(self.frame)
        self.lbl_notice.setGeometry(QtCore.QRect(140, 120, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_notice.setFont(font)
        self.lbl_notice.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_notice.setScaledContents(False)
        self.lbl_notice.setWordWrap(True)
        self.lbl_notice.setObjectName("lbl_notice")
        self.lbl_app_link = QtWidgets.QLabel(self.frame)
        self.lbl_app_link.setGeometry(QtCore.QRect(140, 100, 231, 16))
        self.lbl_app_link.setTextFormat(QtCore.Qt.RichText)
        self.lbl_app_link.setOpenExternalLinks(True)
        self.lbl_app_link.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.lbl_app_link.setObjectName("lbl_app_link")
        self.line = QtWidgets.QFrame(MainWindow)
        self.line.setGeometry(QtCore.QRect(0, 180, 401, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.buttonBox.raise_()
        self.line.raise_()
        self.frame.raise_()

        self.retranslateUi(MainWindow)
        self.buttonBox.accepted.connect(MainWindow.accept) # type: ignore
        self.buttonBox.rejected.connect(MainWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "About Comic Toolbox"))
        self.lbl_title.setText(_translate("MainWindow", "Comic Toolbox"))
        self.lbl_version.setText(_translate("MainWindow", "Version: %s"))
        self.lbl_notice.setText(_translate("MainWindow", "Respect the copyright, please support the genuine version, and the resources downloaded or generated through this tool are prohibited from spreading and sharing! It is prohibited to use this project for commercial activities!"))
        self.lbl_app_link.setText(_translate("MainWindow", "%s"))
from uis import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
