# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crop_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(290, 194)
        MainWindow.setStyleSheet("")
        self.frame = QtWidgets.QFrame(MainWindow)
        self.frame.setGeometry(QtCore.QRect(0, 0, 131, 101))
        self.frame.setStyleSheet("background: rgba(255,255,255,0.8);\n"
"border: 1px solid #00FF00;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_lt = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_lt.sizePolicy().hasHeightForWidth())
        self.lbl_lt.setSizePolicy(sizePolicy)
        self.lbl_lt.setMinimumSize(QtCore.QSize(20, 20))
        self.lbl_lt.setMaximumSize(QtCore.QSize(20, 20))
        self.lbl_lt.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.lbl_lt.setMouseTracking(True)
        self.lbl_lt.setStyleSheet("border-width: 3px 0px 0px 3px;\n"
"background-color: rgba(255,255,255,0);\n"
"")
        self.lbl_lt.setText("")
        self.lbl_lt.setObjectName("lbl_lt")
        self.gridLayout.addWidget(self.lbl_lt, 0, 0, 1, 1)
        self.lbl_rt = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_rt.sizePolicy().hasHeightForWidth())
        self.lbl_rt.setSizePolicy(sizePolicy)
        self.lbl_rt.setMinimumSize(QtCore.QSize(20, 20))
        self.lbl_rt.setMaximumSize(QtCore.QSize(20, 20))
        self.lbl_rt.setCursor(QtGui.QCursor(QtCore.Qt.SizeBDiagCursor))
        self.lbl_rt.setStyleSheet("border-width: 3px 3px 0px 0px;\n"
"background-color: rgba(255,255,255,0);\n"
"")
        self.lbl_rt.setText("")
        self.lbl_rt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_rt.setObjectName("lbl_rt")
        self.gridLayout.addWidget(self.lbl_rt, 0, 2, 1, 1)
        self.lbl_center = QtWidgets.QLabel(self.frame)
        self.lbl_center.setCursor(QtGui.QCursor(QtCore.Qt.SizeAllCursor))
        self.lbl_center.setMouseTracking(False)
        self.lbl_center.setStyleSheet("border: 0px;\n"
"background-color: rgba(255,255,255,0);")
        self.lbl_center.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_center.setObjectName("lbl_center")
        self.gridLayout.addWidget(self.lbl_center, 1, 1, 1, 1)
        self.lbl_lb = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_lb.sizePolicy().hasHeightForWidth())
        self.lbl_lb.setSizePolicy(sizePolicy)
        self.lbl_lb.setMinimumSize(QtCore.QSize(20, 20))
        self.lbl_lb.setMaximumSize(QtCore.QSize(20, 20))
        self.lbl_lb.setCursor(QtGui.QCursor(QtCore.Qt.SizeBDiagCursor))
        self.lbl_lb.setStyleSheet("border-width: 0px 0px 3px 3px;\n"
"background-color: rgba(255,255,255,0);")
        self.lbl_lb.setText("")
        self.lbl_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_lb.setObjectName("lbl_lb")
        self.gridLayout.addWidget(self.lbl_lb, 2, 0, 1, 1)
        self.lbl_rb = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_rb.sizePolicy().hasHeightForWidth())
        self.lbl_rb.setSizePolicy(sizePolicy)
        self.lbl_rb.setMinimumSize(QtCore.QSize(20, 20))
        self.lbl_rb.setMaximumSize(QtCore.QSize(20, 20))
        self.lbl_rb.setCursor(QtGui.QCursor(QtCore.Qt.SizeFDiagCursor))
        self.lbl_rb.setStyleSheet("border-width: 0px 3px 3px 0px;\n"
"background-color: rgba(255,255,255,0);\n"
"")
        self.lbl_rb.setText("")
        self.lbl_rb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_rb.setObjectName("lbl_rb")
        self.gridLayout.addWidget(self.lbl_rb, 2, 2, 1, 1)
        self.lbl_b = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_b.sizePolicy().hasHeightForWidth())
        self.lbl_b.setSizePolicy(sizePolicy)
        self.lbl_b.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.lbl_b.setStyleSheet("border: 0px;\n"
"background-color: rgba(255,255,255,0);")
        self.lbl_b.setText("")
        self.lbl_b.setObjectName("lbl_b")
        self.gridLayout.addWidget(self.lbl_b, 2, 1, 1, 1)
        self.lbl_t = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_t.sizePolicy().hasHeightForWidth())
        self.lbl_t.setSizePolicy(sizePolicy)
        self.lbl_t.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.lbl_t.setStyleSheet("border: 0px;\n"
"background-color: rgba(255,255,255,0);")
        self.lbl_t.setText("")
        self.lbl_t.setObjectName("lbl_t")
        self.gridLayout.addWidget(self.lbl_t, 0, 1, 1, 1)
        self.lbl_l = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_l.sizePolicy().hasHeightForWidth())
        self.lbl_l.setSizePolicy(sizePolicy)
        self.lbl_l.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.lbl_l.setStyleSheet("border: 0px;\n"
"background-color: rgba(255,255,255,0);")
        self.lbl_l.setText("")
        self.lbl_l.setObjectName("lbl_l")
        self.gridLayout.addWidget(self.lbl_l, 1, 0, 1, 1)
        self.lbl_r = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_r.sizePolicy().hasHeightForWidth())
        self.lbl_r.setSizePolicy(sizePolicy)
        self.lbl_r.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.lbl_r.setStyleSheet("border: 0px;\n"
"background-color: rgba(255,255,255,0);")
        self.lbl_r.setText("")
        self.lbl_r.setObjectName("lbl_r")
        self.gridLayout.addWidget(self.lbl_r, 1, 2, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.lbl_center.setText(_translate("MainWindow", "Page"))
from uis import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
