# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reader_rotate_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(280, 121)
        MainWindow.setMinimumSize(QtCore.QSize(280, 120))
        MainWindow.setMaximumSize(QtCore.QSize(280, 121))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/main_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(MainWindow)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_rotate = QtWidgets.QFormLayout()
        self.layout_rotate.setObjectName("layout_rotate")
        self.lbl_target_image = QtWidgets.QLabel(MainWindow)
        self.lbl_target_image.setObjectName("lbl_target_image")
        self.layout_rotate.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_target_image)
        self.cbx_target_image = QtWidgets.QComboBox(MainWindow)
        self.cbx_target_image.setObjectName("cbx_target_image")
        self.layout_rotate.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cbx_target_image)
        self.lbl_rotate = QtWidgets.QLabel(MainWindow)
        self.lbl_rotate.setObjectName("lbl_rotate")
        self.layout_rotate.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_rotate)
        self.cbx_rotate = QtWidgets.QComboBox(MainWindow)
        self.cbx_rotate.setObjectName("cbx_rotate")
        self.layout_rotate.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbx_rotate)
        self.lbl_change_mode = QtWidgets.QLabel(MainWindow)
        self.lbl_change_mode.setObjectName("lbl_change_mode")
        self.layout_rotate.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_change_mode)
        self.cbx_change_mode = QtWidgets.QComboBox(MainWindow)
        self.cbx_change_mode.setObjectName("cbx_change_mode")
        self.layout_rotate.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cbx_change_mode)
        self.verticalLayout.addLayout(self.layout_rotate)
        self.buttonBox = QtWidgets.QDialogButtonBox(MainWindow)
        self.buttonBox.setToolTip("")
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(MainWindow)
        self.buttonBox.accepted.connect(MainWindow.accept) # type: ignore
        self.buttonBox.rejected.connect(MainWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rotate"))
        self.lbl_target_image.setText(_translate("MainWindow", "Target image"))
        self.lbl_rotate.setText(_translate("MainWindow", "Rotate"))
        self.lbl_change_mode.setText(_translate("MainWindow", "Change mode"))
from uis import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
